package com.kirkwoodwest.launchpadminimk3.hardware;

public enum GridButtonColor {
    Off,
    HasClip,
    ClipPlaying,
    ClipPlayingNote,
    AltHasClip,
    AltClipPlaying,
    AltClipPlayingNote,
    SceneHasClip,
    SceneClipPlaying,
    SceneClipPlayingNote,
    SceneAltHasClip,
    SceneAltClipPlaying,
    SceneAltClipPlayingNote,
    StopHasClip,
    StopClipPlaying,
    StopClipPlayingNote,
    NoteRecording,
    NoteOffRecording,
    LaunchNormalMode,
    LaunchAltMode,
    FillModeActive,
    FillModeInactive,
    FillModeBar,
    FillModeLocked,
    SceneModeActive,
    SceneModeInactive,
    StopModeActive,
    StopModeInactive,
    DeleteClipPlaying,
    DeleteClipPlayingNote,
    DeleteHasClip
}
